#ifndef SHADERATTRIBUTE_H
#define SHADERATTRIBUTE_H

enum VertexAttribute {
  POSITION = 1,
  TEXTURE_COORDINATE = 2,
  NORMAL = 3,
  UNIFORM_MVP = 4
};

enum FragmentAttribute {
  UNIFORM_REFLECTIVE_POWER = 5,
  UNIFORM_LIGHT_POSITION = 6,
  UNIFORM_LIGHT_COLOR = 7,
  UNIFORM_OBJECT_COLOR = 8,
  UNIFORM_TEXTURE1 = 9,
  UNIFORM_TEXTURE2 = 10
};

#endif // SHADERATTRIBUTE_H
