#ifndef SHADERATTRIBUTE_H
#define SHADERATTRIBUTE_H

enum VertexAttribute {
  POSITION = 1,
  NORMAL = 2,
  TEXTURE_COORDINATE = 3,
  UNIFORM_MODEL_WORLD = 4,
  UNIFORM_MODEL_PROJECTION = 5
};

enum FragmentAttribute {
  UNIFORM_REFLECTIVE_POWER = 6,
  UNIFORM_LIGHT_POSITION = 7,
  UNIFORM_LIGHT_COLOR = 8,
  UNIFORM_OBJECT_COLOR = 9,
  UNIFORM_TEXTURE1 = 10,
  UNIFORM_TEXTURE2 = 11
};

#endif // SHADERATTRIBUTE_H
