#ifndef SHADERATTRIBUTE_H
#define SHADERATTRIBUTE_H

enum VertexAttribute {
  POSITION = 1,
  NORMAL = 2,
  TEXTURE_COORDINATE = 3,
  UNIFORM_MODEL_NORMAL = 4,
  UNIFORM_MODEL_WORLD = 5,
  UNIFORM_MODEL_PROJECTION = 6
};

enum FragmentAttribute {
  UNIFORM_REFLECTIVE_POWER = 7,
  UNIFORM_SHINE_POWER = 8,
  UNIFORM_LIGHT_POSITION = 9,
  UNIFORM_LIGHT_COLOR = 10,
  UNIFORM_OBJECT_COLOR = 11,
  UNIFORM_CAMERA_POSITION = 12,
  UNIFORM_TEXTURE1 = 13,
  UNIFORM_TEXTURE2 = 14
};

#endif // SHADERATTRIBUTE_H
